# Generated by Django 3.2.25 on 2024-09-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Image Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-image/', verbose_name='Изображение')),
                ('sort_by', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Image Name')),
                ('value', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Value')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sort_by', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Product Parameter',
                'verbose_name_plural': 'Product Parameters',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productimages'),
        ),
        migrations.AddField(
            model_name='products',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productparameters'),
        ),
    ]
